version: '3.8'

services:
  dexterlab-app:
    image: rbmaggi/dexterlab:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "7373:3000"
    restart: always
    nvironment:
      MONGODB_URI: "mongodb://mongo:27017/dexterlab" # Add this line to specify the MongoDB URI

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin # replace here
      MONGO_INITDB_ROOT_PASSWORD: admin # replace here