version: '3.8'

services:
  dexterlab:
    image: rbmaggi/dexterlab:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "7373:3000"
    restart: unless-stopped
    environment:
      MONGODB_URI: "mongodb://mongo:27017/dexterlab" # Add this line to specify the MongoDB URI

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    restart: unless-stopped
    # volumes:
      # - ./data:/data/db
    command: --bind_ip_all
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin # replace here
      MONGO_INITDB_ROOT_PASSWORD: admin # replace here